Level_4/Level_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),

]

Level_4/myapp/urls.py
from django.urls import path, include
from . import views

# NEW: TEMPLATE TAGGING
app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='home'),
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),   
]

Level_4/myapp/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    books=[
        {'title': '1984', 'author': {'name': 'George', 'age': 45}},
        {'title': 'Timequake', 'author': {'name': 'Kurt', 'age': 75}},
        {'title': 'Alice', 'author': {'name': 'Lewis', 'age': 33}},
    ]
    text = {
        "string": "well I'll be a monkey's uncle", 
        "int":100,
        "books":books,
        "list": "My dog is named FRED...BEEYATCH".split(),
        
    } 
    return render(request, 'myapp/index.html', context=text)

def other(request):
    return render(request, 'myapp/other.html')

def relative(request):
    return render(request, 'myapp/relative_url.html')

Level_4/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <!-- corresponds to app_name var: name-->
                <li><a class="navbar-brand" href="{% url 'myapp:home' %}"> Home </a></li>
                <!--Link to admin- uses admin pre-installed app-->
                <li><a class="navbar-link" href="{% url 'admin:index' %}"> Admin </a></li>
                <li><a class="navbar-link" href="{% url 'myapp:other' %}"> Other </a></li>
            </ul>
        </div>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myapp:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
        <!--Anything outside inherited by all-->

    </div>
</body>
</html>

Level_4/templates/myapp/index.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}

    {%block title%} Home {%endblock%}

    {% block body_block %}

    <a href="https://docs.djangoproject.com/en/3.0/howto/custom-template-tags/#howto-writing-custom-template-filters"> Custom filter tags docs </a>
    <br> <br>
    <h1>Welcome to Index! </h1>
    <a href="{% url 'myapp:relative' %}"> Relative urls!</a>
    <h3>String: {{string|upper }}</h1>
    <h3>Number: {{ int|add:"5" }}</h3>
    <h5>
    {% for book in books %}
        <p>{{ book.title }} ({{ book.author.name }}) </p>
    {% endfor %}
    </h5>
    <h4> {{list|join:" *&* "}}</h4>
    <h4>{{ list|slice:"0:4"}}</h4>

    {% endblock %}
</body>
</html>

Level_4/templates/myapp/other.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}

    {% block body_block %}
        <h1>Welcome to other!</h1>
        <p>Template inheritance amazing!</p>
    {% endblock %}

Level_4/templates/myapp/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative url!</h1>
    <a href="{% url 'myapp:other' %}"> Link to other </a>
</body>
</html>